name: Build AAB

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip mercado_android_app-3.zip

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission
        run: chmod +x ./mercado_android_app/gradlew

      - name: Build AAB
        run: |
          cd mercado_android_app
          ./gradlew bundleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: MercadoEnLineaCuliacan
          path: mercado_android_app/app/build/outputs/bundle/release/app-release.aab
