name: Build AAB

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip mercado_android_app-3.zip

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build AAB
        run: |
          cd mercado_android_app-3
          gradle bundleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: MercadoEnLineaCuliacan-AAB
          path: mercado_android_app-3/app/build/outputs/bundle/release/*.aab
